### ISSUE TITLE
Keyword search of data used for interactive maps

### ISSUE THREAD

**Issue by Stefankirby** [UGS-GIO/geolMapPortal#81]
### Why do you feel this application needs what you're requesting?

This would facilitate quickly finding a instances of a given thing of interest  examples "Rico Formation"  or "Travertine" or "Rowley" etc.

### Describe the solution you'd like and why it builds value

Turns the interactive map into a very powerful research tool.

### What impact will this new functionality have on this application's audience?

Would greatly increase use of interactive map for research.

### How Urgent is this?

Low

### Please provide additional evidence from other users to support medium and high ranking

See chat

**Comment by marshallrobinson** [comment]
This sounds like a pretty awesome feature that would possibly hinge on massaging the geologic polygon feature classes into a single feature class in order to speed up the query. Possibly...to be continued. 

Others (@lance-weaver, @marthajensen, @JP-GEO), feel free to chime in. I think that accomplishing this feature would open up the possibility to do many other projects we've talked about (an authoritative, internal Wiki of geologic formations is the first to come to mind).

**Comment by lance-weaver** [comment]
This feature is somewhat implemented but will be something we tackle after we switch all our vector layers to a mater db

**Comment by Stefankirby** [comment]
Issue has been addressed until all layers are combined in future webmap version.  Good to close for now. @marshallrobinson
