### ISSUE TITLE
Ksl layer not working

### ISSUE THREAD

**Issue by jmulhernUGS** [UGS-GIO/geolMapPortal#86]
### What happened?

Straight cliffs formation doesnt search accurately, missing big swaths from adjacent map
![image](https://user-images.githubusercontent.com/115105122/194124115-d58cfd5e-dd59-4a78-8486-9dd2beabce22.png)

### What did you expect to happen?

whole lyr show up

### Browser Version

chrome

**Comment by marshallrobinson** [comment]
I believe Lance spoke with you about this bug and why it happens? Selecting one of the suggested geologic units will return the units from a specific mapped quad. In order to return geologic units across multiple quads, I find it is more accurate to type the name of the unit (w/o "formation" or "member") and then hitting "enter".

The geologic unit search is a work in progress, and is completely dependent on consistent data between each mapped quad....which we're hoping to accomplish in the next year or so.

**Comment by jmulhernUGS** [comment]
yes he did. I'm looking forward to once its working fully. I was telling
Lance it would be great to be able to download just specific formations.
Thanks for working on this!
